spring:
    profiles.active: dev

################################  
# dev profile section  #
################################

---
spring:
    profiles: dev
    
    datasource:
        url: jdbc:h2:~/example;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        test-while-idle: true
        validation-query: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        generate-ddl: true


endpoints:
    health:
        sensitive: false
        enabled: true
    actuator:
        enabled: true


###############################
# QA profile section  #
###############################

---
spring:
    profiles: qa

    datasource:
        url: jdbc:mysql://192.168.0.190:3306/membersystem?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: 123456
        test-while-idle: true
        validation-query: SELECT 1
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        generate-ddl: true

###############################     
# prod profile section  #
###############################

---
spring:
    profiles: prod
    

###########################
# default profile section #
###########################
---        
logging:
    level:
        com.upbchain: DEBUG

security:
    ignored: /**
    basic.enabled: false
management:
    security.enabled: false